name= input("Enter a name: ")
adj1= input("Enter an adjective: ")
adj2= input("Enter an adjective: ")
adverb= input("Enter an adverb: ")
food= input("Enter a food: ")
food2= input("Enter another food: ")
noun= input("Enter a noun: ")
place= input("Enter a place: ")
verb= input("Enter a verb: ")

print("Let's play Silly Sentences!\n")
print(name + " was planning a dream vacation to " + place + ".\n")
print(name + " was especially looking forward to trying the local\ncuisine, including " + adj1+" " + food +" "+ "and " + food2 + ".\n")
print(name + " will have to practice the language " + adverb + " to\nmake it easier to " +verb + " with people.\n")
print(name + " has a long list of sights to see, including the\n" + noun +" museum and the " + adj2 +" park.")
